name: Auto Merge
on: [pull_request]
permissions:
  pull-requests: write
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install, build, and upload your site output
        uses: withastro/action@v0
